### ISSUE TITLE
User Stupidity

### ISSUE THREAD

**Issue by ShadowofCubes** [ixjf/MSIRGB#1]

**Comment by ixjf** [comment]
Does that mean it's working?

**Comment by ShadowofCubes** [comment]
I just forgot to grant the programm admin rights. It's working on my Tomahawk B350. Thank you. Stupid msi shit.

**Comment by ixjf** [comment]
Great, thanks!

I'm considering writing a GUI wrapper for this. Should be more intuitive to Windows users.

**Comment by ixjf** [comment]
Hi. Please see the https://github.com/ixjf/MSIRGB again. I just commited a major change which includes a GUI. Shouldn't have a problem anymore with not having administrator rights as well.

**Comment by ShadowofCubes** [comment]
That new GUI looks really nice. Could you please upload a compiled version of this? I don't have Visual Studio installed right now...

**Comment by ixjf** [comment]
My bad. I forgot to upload the file. Duh! Here: https://github.com/ixjf/MSIRGB/releases/download/v1.0.0/MSIRGB-v1.0.0.zip

**Comment by ShadowofCubes** [comment]
Thanks, it's really late here in Germany, I will look at it tomorrow.

**Comment by ShadowofCubes** [comment]
Okay. I've found no issues so far, exept the high cpu utilization while using the "rainbow" script (I have 12 logical cores, so 10% is a lot): https://prnt.sc/lrnv99

**Comment by ShadowofCubes** [comment]
Even if that script is empty or os.sleep() is set to 10000 the cpu utilization stays the same.
(When the script is empty it's even higher, about 25%)
The old Python script worked great and only used around 1%.
Maybe your programm is "starting" the script to often?[Sorry if I write absolute bullshit] Even if the script doesn't include a loop, it still runs forever like it's looped.

**Comment by ixjf** [comment]
Right, I think I know what the problem is. The script service runs an infinite loop waiting for a shutdown signal for the script thread. There's no wait in between each execution, which is consuming too much time. Should be a 10 second fix, but I'll have to do that tomorrow morning.

**Comment by ixjf** [comment]
Hi. Problem is fixed. See the latest release. Thanks for reporting!
