### ISSUE TITLE
"require" function in scripts

### ISSUE THREAD

**Issue by dbodyas** [ixjf/MSIRGB#102]
Is there a way to use `require` function in lua scripts? I want to load "socket" library and send data over udp.

**Comment by ixjf** [comment]
This is fixed in commit 48d7e96acd5a1df87f4711aaf3d7a18393a40c99. I'll publish a new release soon.

*Note to myself: Update wiki to reflect changes. Explain how this can allow users to do random stuff without me needing to implement it myself.*

**Comment by ixjf** [comment]
Done and closing this issue.
