### ISSUE TITLE
MSI B450 Gaming Pro Carbon AC

### ISSUE THREAD

**Issue by pguerrerox** [ixjf/MSIRGB#103]
Has anyone get this software working on this motherboard?  i need an alternative to mystic light.

**Comment by MrPalamen** [comment]
+1

**Comment by ixjf** [comment]
Why doesn't it work?

**Comment by benchebanianas** [comment]
@pguerrerox i am getting this 

![msi](https://user-images.githubusercontent.com/16312432/83558707-b4881400-a513-11ea-9f8a-4607e6e1bda9.png)

**Comment by ixjf** [comment]
Can you run this command on a command prompt:

`wmic path Win32_BaseBoard get Manufacturer`

and provide me with the result?

**Comment by MrPalamen** [comment]
Manufacturer
Micro-Star International Co., Ltd.

**Comment by aaronthew** [comment]
Same here on the b450 Gaming Pro Carbon AC  
wmic path Win32_BaseBoard get Manufacturer
Manufacturer
Micro-Star International Co., Ltd.

**Comment by benchebanianas** [comment]
@ixjf i found out why i was having this problem: basically i am also running MacOs in my computer and it changes the Motherboard manufacturer name in order to boot. After changing the bios to the Windows 10 one it runs normally

**Comment by aaronthew** [comment]
@benchebanians that's for the update, I don't have Macos on my pc but will look into bios issues

**Comment by ixjf** [comment]
In the cases where WMI returns the correct manufacturer, I'm not sure why it is not working. Unfortunately, I can't debug this until end of July/start of August since I don't have access to my work desktop :/

**Comment by XenSide** [comment]
I can confirm that this board is incompatible. 
I can run the program just fine without errors but applying colors or scripts does nothing at all

**Comment by ixjf** [comment]
Indeed, it is.
