### ISSUE TITLE
Problem load driver

### ISSUE THREAD

**Issue by cassiokennedy** [ixjf/MSIRGB#104]
Can someone help me? Failed to load the b450 network card driver and I was able to use the program only once, when the new opening appears in the following message "Failed to load the driver. This may be due to some program interfering with the MSIRGB driver"

**Comment by ixjf** [comment]
It most likely means you have some other program that is using _inpoutx64_ as well, the driver MSIRGB uses to control the hardware. Do you have any software installed for controlling some hardware, other than MSI's?

**Comment by cassiokennedy** [comment]
I uninstalled everything and the software opened, but I choose the color for example red and it is blue. Could it be incompatibility?

**Comment by ixjf** [comment]
Which motherboard do you have?

**Comment by cassiokennedy** [comment]
MSI b450 Tomahawk

**Comment by ixjf** [comment]
It has been previously reported that for some motherboards **(including yours)**, the colour codes are inverted. Unfortunately I can't work on MSIRGB at the moment, otherwise I would have pushed a fix already.

**Comment by cassiokennedy** [comment]
No problems and congratulations for the project

**Comment by velasd4** [comment]
If you have Riot Vanguard installed, turn it off then try opening MSIRGB again.
