### ISSUE TITLE
MSI GAMING M6 AC - Compatible

### ISSUE THREAD

**Issue by unkollbro** [ixjf/MSIRGB#109]
Hi everyone.
MSIRGB is also compatible with the Z270 MSI GAMING M6 AC motherboard, just disable the VALORAN/RIOT VANGUARD Launcher and it will start.

![Image of MSI GAMING M6](https://i.postimg.cc/J7x6G6Nb/image.png)

**Comment by ixjf** [comment]
Thanks!
