### ISSUE TITLE
Extreme user stupidity

### ISSUE THREAD

**Issue by tjf801** [ixjf/MSIRGB#11]
Hi, I haven't really programmed in C++ before, so I can't even find the file I'm supposed to run or know how to run it. If anyone could help that would be cool. :P

**Comment by ixjf** [comment]
What are you trying to do? Run the tool? All you have to do is go here: https://github.com/ixjf/MSIRGB/blob/master/README.md#how-to-install and follow the instructions.

**Comment by tjf801** [comment]
I installed VC and extracted the folder to my desktop, but I have no idea what to do from there.

**Comment by tjf801** [comment]
Oh wait. I just figured it out lol.
