### ISSUE TITLE
Support for msi x570 gaming pro carbon

### ISSUE THREAD

**Issue by jguzman-ar** [ixjf/MSIRGB#117]
Hi @ixjf !! great job building this solution to replace crappy mystic light/DC soft.

Any chance to work on new x570 chipset based motherboards. I personally own a msi x570 gaming pro carbon and gladly help you out testing a new release to provide support.

Thanks in advance and keep it up!!

**Comment by ixjf** [comment]
I would need to do some research first, but thanks for the support.
