### ISSUE TITLE
Add support for effects based on Windows audio

### ISSUE THREAD

**Issue by khalidwaleed0** [ixjf/MSIRGB#119]

**Comment by fabroos** [comment]
any library to get system audio information? such as frequency or something?

**Comment by ixjf** [comment]
A quick Google search got me here: https://github.com/naudio/NAudio

**Comment by ixjf** [comment]
I won't be adding this feature to MSIRGB, but other people are welcome to send a pull request.

**Comment by ixjf** [comment]
Maybe this can be done now in Lua since you can load 3rd party Lua modules?

**Comment by ixjf** [comment]
Any update on this?
