### ISSUE TITLE
"Failed to load driver" error.

### ISSUE THREAD

**Issue by M0drah** [ixjf/MSIRGB#122]
I have followed the directions, I have all my folders done correctly as shown in the readme. 
When I click on "MSIRGB.exe" to run it, the User Account Control comes up, I click "yes" and almost immediately get this error: 

"Failed to load driver. This could be either due to some program interfering with MSIRGB's driver, or it could be a bug. Please report this on the issue tracker at https://github.com/ixjf/MSIRGB"

![image](https://user-images.githubusercontent.com/66933179/84617273-09bd1180-ae94-11ea-9074-e2bffc2b50b4.png)

My folders:
![image](https://user-images.githubusercontent.com/66933179/84617290-16416a00-ae94-11ea-938f-b35cb02699af.png)

![image](https://user-images.githubusercontent.com/66933179/84617307-1d687800-ae94-11ea-969b-8fe525279a21.png)

Is there something I'm doing incorrectly?

Thanks!
M0drah

**Comment by ixjf** [comment]
Likely you have another program blocking the driver from loading. Riot Vanguard and other programs that control hardware might be the root cause.

**Comment by nyxmon** [comment]
This definitely sounds like Vanguard or similar "anti-cheat" program interfering. It shows the exact same error on mine when I start **MSIRGB.exe** (whilst Vanguard is running).

**Comment by jsftv** [comment]
Can confirm. Riot Vanguard is blocking mine now, as well.

**Comment by ixjf** [comment]
Did you fix the issue?

**Comment by M0drah** [comment]
I did. It ended up being the anti-cheat for Valorant causing it. I have
since uninstalled Valorant and the software. My motherboard does not have
the colors I thought it did.

**Comment by ixjf** [comment]
Alright, thanks. Vanguard is an issue I still need to handle.
