### ISSUE TITLE
MSI Gaming Plus Max also has the reversed color issue 

### ISSUE THREAD

**Issue by psisquared2** [ixjf/MSIRGB#123]
As the title says, the MSI Gaming Plus MAX is also affected by #106. This is in contrast to the non-MAX version which someone else reported to work without issue.

Interestingly, the MSI Mystic Light tool also applies reversed colors even after I close MSIRGB. It is only fixed after a reboot.

Please let me know if I can help by providing further information to add this mainboard to the supported list.

**Comment by ixjf** [comment]
MSIRGB v2.3.0 fixes the reversed colour issue. Please try the new version.

**Comment by ixjf** [comment]
Closing as it is a duplicate of #139.

**Comment by psisquared2** [comment]
I can confirm that the B450 MSI Gaming Plus MAX now works as intended. Thank you!

**Comment by ixjf** [comment]
Great, thanks for the feedback!
