### ISSUE TITLE
Reversed colours fix does not apply to motherboards not currently whitelisted by MSIRGB

### ISSUE THREAD

**Issue by chururi** [ixjf/MSIRGB#126]
Hi, i have a B350m Mortar Arctic. I have installed the VC Redist 2017 x64. After i downloaded the 'latest release', the (MSIRGB-v2.2.1.2.7z), after i try to click on it. This following messagge appeared.

"This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings page."

So what is this 'App' its talking about? I have tried to download the GamingApp and MSI Command Center. But still this message appeared. What can i do for now? Will be waiting for the reply. Thanks.

**Comment by ixjf** [comment]
You need a file archiver installed, like 7-Zip or WinRar, to open these kinds of files. I assumed everyone would have one installed already, but in the future, I'll try to package releases in the ZIP format that can be opened without the need for third-party applications.

**Comment by chururi** [comment]
Of course it is! This PC was actually build yesterday. I still didn't have WinRAR.
Everything works perfectly, except the color isn't the same as what i input. For further info, i didn't know if the color is reversed or not. I put it as purple, but it came out as white  pinkish. Thanks again for the help, sir!

**Comment by ixjf** [comment]
Which motherboard is it?

**Comment by chururi** [comment]
It's B350m Mortar Arctic

**Comment by ixjf** [comment]
Alright, thanks. Will look into that issue ASAP.

**Comment by chururi** [comment]
Thank you so much for the support.

**Comment by ixjf** [comment]
MSIRGB v2.3.0 fixes the reversed colour issue. Please try the new version.

**Comment by ixjf** [comment]
Although MSIRGB v2.3.0 fixes this issue, this motherboard is not on the list of supported motherboards, hence the fix doesn't apply. I'll try to fix that soon.

**Comment by ixjf** [comment]
Fixed! (or I hope so - do test to make sure).
