### ISSUE TITLE
Music Sync

### ISSUE THREAD

**Issue by prameenson** [ixjf/MSIRGB#127]
The application works flawlessly, the only thing I miss is the music sync.
Can someone please help me with a script for the same?
Thanks in advance :)

**Comment by FiddleStickers** [comment]
+1

also I wish to know if this supports MSI graphics cards, as I want to get rid of Dragon Center =)

**Comment by ixjf** [comment]
Closing as it is a duplicate of #119. Please refer to that issue for status information.
