### ISSUE TITLE
It wont start 

### ISSUE THREAD

**Issue by bit-greg** [ixjf/MSIRGB#129]
So recently i wanted to install MSIRGB. I already had it working on another machine withe the same Mainboard (MSIM-Pro-VDH), but now i cant open it. As soon as I try opening it, it asks for admin rights but then it dissapears immediately. Also it doesn´t show up in Task Manager. I have no Idea why it wont work since it already worked on the same mainboard and ive VCRedist installed.
Thx for help.

**Comment by ixjf** [comment]
I'm sorry for the delayed response. Did you get it fixed?

**Comment by bit-greg** [comment]
Yup finally got it. There were some corrupted files in my operating system that after reinstalling windows were finally fixed. I think it was some kind of driver issue that caused the problem. Am 19.08.2020 18:56 schrieb Pedro Fanha <notifications@github.com>:
I'm sorry for the delayed response. Did you get it fixed?
