### ISSUE TITLE
Driver load failed, prob related to Riots Vanguard?

### ISSUE THREAD

**Issue by wughuf** [ixjf/MSIRGB#131]
Hello there, 
i wanted to try this out with my b450 tomahawk max cause msi's dragoncentre sucks but i ran into the following issue (screenshot down there). At the same time when i tried to install it riots vanguard gave me a notification that it would have to be disabled or sth, dont remember it exactly (screenshot down there too). I didnt try yet to disable vanguard and install it and then enable vanguard again but thought this might be interestin so im putting it up here. 

![grafik](https://user-images.githubusercontent.com/68469987/87853694-794b7400-c90c-11ea-8264-20c7d998f77e.png)
![grafik](https://user-images.githubusercontent.com/68469987/87853733-eb23bd80-c90c-11ea-8b5a-065ec55738d7.png)

**Comment by wughuf** [comment]
okay i just saw there is already a thread on this and no solution yet, sorry for opening another one

**Comment by ixjf** [comment]
No problem.
