### ISSUE TITLE
Add command line parameters to control LEDs using third-party scripts

### ISSUE THREAD

**Issue by alchemistake** [ixjf/MSIRGB#137]
I want to write a script to enable/disable light and as the luck goes I have to use 2 different apps for 2 different lights (AMD Wraith Prism + MSI MB)

Can I use this software from command line?

**Comment by ixjf** [comment]
Currently, no.

**Comment by ixjf** [comment]
Hey, would it work if you could instead execute commands from the Lua script? You can use os.execute to execute command line code.

**Comment by ixjf** [comment]
Anyone has any opinions on this?
