### ISSUE TITLE
RGB not Working

### ISSUE THREAD

**Issue by thexihad** [ixjf/MSIRGB#138]
I have msi b450 tomahawk max.After using This app . MSI mystic Light is not working.The only color I can see is Red Or I can disable all effects To turn off lights.

My Mobo is bricked?? 
How can I fix it to use MSI mystic Light again?
Please help guys.

**Comment by ixjf** [comment]
Shutdown your computer. Turn off the power supply. Press the power button for about 10 seconds. Turn the PC on again. Should get everything working again. Alternatively, remove the CMOS battery for a few minutes, then put it back on.

**Comment by thexihad** [comment]
Okay I'm doing it right now

**Comment by thexihad** [comment]
After doing that ..Msi Dragon center is loading.. Initialization.
![15984630029814282539073715062951](https://user-images.githubusercontent.com/52651148/91336700-219a0580-e7f4-11ea-8649-8b68c5e75cc2.jpg)

**Comment by thexihad** [comment]
No bro it's not working .. If I choose any effect in Mystic light ..Only red is showing ,and then turning off sometimes. No other Colors. What else can I do?? 

When I used you App first time it showed other colors too.. But then I choose disable all effects.. I don't know after that..The only color shown is red.

**Comment by ixjf** [comment]
You probably didn't press the power button for enough time. Either try repeating the process or use the alternative process - remove the CMOS battery for about 10 minutes, then put it back on.

**Comment by thexihad** [comment]
I removed the cmos battery for 3-4 mins. I'll try again Today and let you know .I hope it works.

**Comment by ixjf** [comment]
Did you fix it?

**Comment by thexihad** [comment]
No bro it's not fixed. I gave up I don't know what to do. And there's no new bios update available. Otherwise I would have tried updating BIOS. 
Is there anything else that I can do?

**Comment by ixjf** [comment]
I don't think you're doing the process right. I think it's very unlikely MSIRGB could do any irreversible damage on the motherboard. Could you repeat the first process just to make sure? And be patient. Power supply OFF. Press the power button on the case for *at least* 10 seconds. Then turn everything on again.

If this still doesn't work, I'll try to see what I can do. But it should be fixable.

**Comment by thexihad** [comment]
Okay bro I will do the process again Tomorrow . Pressing power button and Removing cmos battery for 10 min also... I will let you know... And Did anyone use MSIRGB with B450 Tomahawk max and had no problem?? . First time the colors were changing with MSIRGB..But after that it's Red Only... I'll do the processes And let you know again.

**Comment by ixjf** [comment]
The problem you describe has been reported to happen on that motherboard. MSIRGB won't work properly with it _at this time_. However, no one has complained that they couldn't get lights to work properly again.

**Comment by thexihad** [comment]
![20200831_104853](https://user-images.githubusercontent.com/52651148/91684256-c01dc200-eb78-11ea-8c7c-e8d2d6408e8b.jpg)
![20200831_105147](https://user-images.githubusercontent.com/52651148/91684263-c6ac3980-eb78-11ea-99f8-156ce9091124.jpg)
![20200831_105515](https://user-images.githubusercontent.com/52651148/91684285-daf03680-eb78-11ea-95d4-d7a5803b8977.jpg)
![20200831_105600](https://user-images.githubusercontent.com/52651148/91684290-df1c5400-eb78-11ea-9f41-ba97d3c5ba04.jpg)
![20200831_105620](https://user-images.githubusercontent.com/52651148/91684293-e2174480-eb78-11ea-95e5-884d0abfce54.jpg)

Look Brother . Removed battery for more than 10 mins. 
Now I'm using A lite version windows 10 . It's missing powershell so I can't check with Mystic light .So I want to use MSIRGB but you just look at the ui Does it look all right? Cause there's no Script. 
Or can You send Me the proper MSIRGB with scripts I'll download it from Gdrive if you can.

**Comment by ixjf** [comment]
Did you download the scripts?

**Comment by thexihad** [comment]
Yes but I don't know how to use them.😰

**Comment by ixjf** [comment]
Did you follow the instructions on the main page on how to setup MSIRGB?

**Comment by thexihad** [comment]
Update #
Color is Changing using scripts ..But colors looks
Very fake I mean not very good.. I'll send you video. And fan speed is varying while Changing colors (This can Harm my fan) slowing down while Changing colors

**Comment by thexihad** [comment]
![20200831_174330](https://user-images.githubusercontent.com/52651148/91716472-8ddc8680-ebb1-11ea-82f9-626a285c87de.jpg)
I turned of other effects because of the changes in fan speed. 
And I can't use Any SINGLE COLOR option.
Those 8 slots are black and when I customize it only show white.

And in my Case fan I see multiple color LED thats why I think color not looking good.Never saw that before.

**Comment by ixjf** [comment]
Well, I'm glad the motherboard is working properly.

Now, as I said, MSIRGB does not support your motherboard at the moment. I'll try to add support ASAP, but can't promise anything.

**Comment by thexihad** [comment]
I hope you'll add it . Will be waiting 🌹
