### ISSUE TITLE
LEDs show colours reversed

### ISSUE THREAD

**Issue by FluorescentGreen5** [ixjf/MSIRGB#139]
Since the B450 Tomahawk MAX has been recommended a lot for people who are building a system, it would be a good idea to have explicit support added for it. Right now, it will sometimes work (with inverted colours), cause the motherboard to cycle between colours even when you have every square the same colour or even do nothing at all.

**Comment by ixjf** [comment]
I'll work on it ASAP.

**Comment by ixjf** [comment]
As regards inverted colours, that's fixed, and I'll be releasing an updated version of MSIRGB with the fix later today. When it comes to the other issues, I see no reason for that to happen, other than that you may have some other program interfering with the LEDs.

**Comment by ixjf** [comment]
Could you try the new version 2.3.0?

**Comment by FluorescentGreen5** [comment]
Tried it just now. Colours are no longer inverted and it was able to set the LEDs with no hiccups.

**Comment by ixjf** [comment]
Great!
