### ISSUE TITLE
Are any of the MSI z490 boards compatible?

### ISSUE THREAD

**Issue by ELG-Icefish** [ixjf/MSIRGB#145]

**Comment by WHCTHBD** [comment]
I see you closed the issue. Did you test this?

**Comment by ELG-Icefish** [comment]
I tried it on my mpg z490 gaming plus and it didnt work, i also one of my friends tried it on his mag z490 Ace, so i assumed it wont work for any of the z490 ones

**Comment by ixjf** [comment]
There may be Z490 motherboards for which it will work, but I cannot give you a list. The list on the README are the ones that I'm sure are compatible (though it might still not work correctly due to a bug in MSIRGB, since not all motherboards have been tested).
