### ISSUE TITLE
"Failed to load driver."

### ISSUE THREAD

**Issue by profpenguin** [ixjf/MSIRGB#148]
"Failed to load driver. This could be either due to some program interfering with MSIRGB's driver, or it could be a bug. Please report this on the issue tracker at [link]"
This is on a Tomahawk B450 motherboard.
Any ideas?

**Comment by ixjf** [comment]
Do you have Riot Vanguard installed?

**Comment by sv1k** [comment]
Got same error

**Comment by ixjf** [comment]
I'm closing this issue as no further info has been provided. Please comment if you still need help.
