### ISSUE TITLE
Only affecting MB Function LEDs on MSI Z370 Gaming Pro Carbon

### ISSUE THREAD

**Issue by RageFlow** [ixjf/MSIRGB#150]
The MB Function LEDs on the MSI Z370 Gaming Pro Carbon motherboard is a Red colored LED.
So as of now, that board is not "supported".  ;)

(Feel free to remove this after author has seen it :b )

**Comment by ixjf** [comment]
Are your LED strips connected to the 5050 12V connectors or the WS2812B/CORSAIR connectors?

**Comment by RageFlow** [comment]
WS2812B connector and the RGB ligting on the Motherboard itself is not affected by MSIRGB (Except the MB Funtion LEDs)

**Comment by ixjf** [comment]
I would have assumed that it would affect the 5050 LED strips, but it's highly unlikely to control the WS2812B connectors, and especially not the CORSAIR one, as these are controlled by separate chips. I'll investigate further about the 5050 connector when I can.

**Comment by RageFlow** [comment]
I just went through some log files for Dragon Center (Mystic light), and noticed it was talking about "MB_Model_hex: 7B45"
I don't know if it helps, but if you need me to check some files just hit me up :)

**Comment by ixjf** [comment]
I'm aware, but thanks :) Will do.

**Comment by ixjf** [comment]
Potentially fixed by #193. If you're willing to try an experimental release, feel free to tell me if it fixes the issue.

**Comment by ixjf** [comment]
Hey. So, I took a closer look and this motherboard is actually not supposed to be supported. It was my mistake to list it as supported. Sorry.
