### ISSUE TITLE
Failed to load driver on B450M Mortar Max

### ISSUE THREAD

**Issue by baoolann** [ixjf/MSIRGB#153]
Hi, 
Can you help me with this problem ?
![image](https://user-images.githubusercontent.com/72617392/95598854-8e9eed00-0a7a-11eb-98a1-b95b5c10380a.png)

**Comment by ixjf** [comment]
If you have Riot Vanguard installed, that may be the issue. Vanguard blocks MSIRGB because it thinks it's a cheat.

**Comment by baoolann** [comment]
It working. Thank you very much !
