### ISSUE TITLE
AMD TRX40

### ISSUE THREAD

**Issue by ctrlaltdude** [ixjf/MSIRGB#154]
I tried running this on my MSI TRX40 but unfortunately it doesn't work. This surprises me because I would assume that MSI doesn't change their RGB setup with every new mainboard.
I looked through the code but I can't program C++ so I don't understand the workings of this.

Could you please add support for the AMD TRX40 chipset? 

Thank you.

**Comment by ixjf** [comment]
> This surprises me because I would assume that MSI doesn't change their RGB setup with every new mainboard.

You would be surprised. Even different revisions of the same motherboard model work differently. For some models, older revisions are not compatible, but newer revisions are.

Can you run this command on the command line so I know which model and revision we are talking about exactly?

`wmic path Win32_BaseBoard get Product, Version`

**Comment by ctrlaltdude** [comment]
Really?! That's nuts!

Here's the info:
Product                   Version
TRX40 PRO WIFI (MS-7C60)  1.0

**Comment by ixjf** [comment]
Alright, I'll check it out and tell you if it's possible to add support for this motherboard (theoretically, it is, the question is whether it uses the same chip or it would require entire new code to control it).

**Comment by ctrlaltdude** [comment]
Cool! Don't put too much effort in it. I don't think the TRX40 chipset is used by many people.

**Comment by ixjf** [comment]
Hi. Sorry, I can't add support for this motherboard :(

**Comment by ctrlaltdude** [comment]
No problem.
Thanks for looking into it!
________________________________
