### ISSUE TITLE
Compatibility 

### ISSUE THREAD

**Issue by PoizenBlood** [ixjf/MSIRGB#155]
Was wondering if their was any plans to add support for B550 MAG Tomahawk, as this seems like exactly what I’m looking for, but it is not working at all for me, also thank you for the work put into this.

**Comment by ixjf** [comment]
It depends on whether I can reuse the existing code or need new code to control a different chip. I won’t really have time in the coming weeks, though.

**Comment by PoizenBlood** [comment]
Completely understandable, thanks for the reply, and the great work.

**Comment by Fredoias** [comment]
If possible, when/if you get a chance. I have a B460m Mortar WiFi and was curious if it could be added? Thanks for the work you do.

**Comment by ixjf** [comment]
I'm not planning on adding support for new motherboards, sorry. Maybe OpenRGB will do the trick?
