### ISSUE TITLE
Support for Z490 chipset motherboards

### ISSUE THREAD

**Issue by UGHGB** [ixjf/MSIRGB#160]
This would be most welcome.
I have MSI Z490 Gaming Plus mobo, CM SickleFlow aRGB fans and Bitfenix Alchemy aRGB strips waiting for software control.

**Comment by ixjf** [comment]
I can't guarantee I can add support for that motherboard. Either way, I don't have the time right now to work on MSIRGB, but I'll leave the issue open for when I can. Thanks!

**Comment by bennodxb** [comment]
I need z490 too. The msi software is so annoying. Thanks for considering it.

**Comment by juicebadwik84** [comment]
Yes please... Would be so awesome if I could use this software with my MPG Z490 Gaming Edge Wifi mobo.  At any point when you have time would be appreciated.

**Comment by mopperizer** [comment]
Meg 490 Unify here. Would love to see an update :)

**Comment by WHCTHBD** [comment]
Z490-A Pro here. Hoping to see it working without Dragon Center soon!

**Comment by CZonin** [comment]
Meg Z490i Unify here, would love to use this!

**Comment by pawel-zajac** [comment]
Z490 Gaming edge wifi here. Is it confirmed it won't work with Z490 boards as is, or does it require checking?

**Comment by ixjf** [comment]
Likely doesn't, but not sure. I have not gotten any reports of it working anyway.

**Comment by WoB666** [comment]
I join with the request for Z490 Gaming edge wifi

**Comment by ixjf** [comment]
Sorry, I'm not planning to add support for any new motherboards.
