### ISSUE TITLE
It is possible to turn on and off lights with for example bat file

### ISSUE THREAD

**Issue by SmoGroove** [ixjf/MSIRGB#168]
I want to turn on and off my strip with script file, then i would use key bindings program and use shortcuts to turn on or off my led.
Sorry for my English

**Comment by ixjf** [comment]
It is not, but I'm considering adding a command-line interface so that this will be possible in the future. Please refer to #137 for the status on the implementation.

**Comment by SmoGroove** [comment]
ok thanks. I'll be waiting :D
