### ISSUE TITLE
Your MB not on the list, then failed to load drivers.

### ISSUE THREAD

**Issue by mbalci420** [ixjf/MSIRGB#170]
Hi. I got msi b450-pro-m2-max. I am trying to load the program and following all the instructions exactly but, when I start msirgb.exe it says your motherboard not on the list, and then I click to continue, it fails again and warns me that failed to load drivers. What can I do ? Help pls.
![msi 4](https://user-images.githubusercontent.com/76042921/102202617-99da2300-3ed8-11eb-8cc9-f4aab0d1830c.jpg)
![msi1](https://user-images.githubusercontent.com/76042921/102202620-9a72b980-3ed8-11eb-94b8-a24c965acf72.png)
![msi2](https://user-images.githubusercontent.com/76042921/102202621-9b0b5000-3ed8-11eb-9622-aba8e7982759.png)
![msi3](https://user-images.githubusercontent.com/76042921/102202622-9b0b5000-3ed8-11eb-9316-079278914d3e.png)

**Comment by ixjf** [comment]
Do you have any anticheat installed? Vanguard, FACEIT, etc.

**Comment by mbalci420** [comment]
Nope. I don't have any of them.

**Comment by mbalci420** [comment]
Can anyone please help me? :(

**Comment by ixjf** [comment]
https://github.com/ixjf/MSIRGB/issues/132#issuecomment-674405037

Can you try this debug build and tell me the output of the debug log? (Explained there how to do that)

**Comment by mbalci420** [comment]
The same thing happend. 
Debug_log :
start_drv: StartService failed with error 647
load_drv: start_drv() != ERROR_SUCCESS
load_drv failed

**Comment by ixjf** [comment]
This sort of error is usually caused by some program interfering with MSIRGB's driver. Can you try running MSIRGB in a sort of 'safe mode' boot? Just disable all non-Windows services and startup items (from 'msconfig' and Task Manager) and reboot, then try.

**Comment by mbalci420** [comment]
Nope :( Sorry but the same thing happened again. I'm done with it and sick of this trash motherboard. Thanks for your struggle. Happy new year.

**Comment by ixjf** [comment]
I guarantee that's not a problem with your motherboard, though it is possible MSIRGB won't support your motherboard either way. If you have any games installed, I suggest you check if they don't include any anti cheat.

Happy New Year.

**Comment by ixjf** [comment]
Did you fix this?

**Comment by mbalci420-hub** [comment]
Nope I didn't

**Comment by ixjf** [comment]
Can you open a command prompt and run these commands?

```sc query type=driver > drivers.txt
tasklist > userprc.txt```

It should create the files 'drivers.txt' and 'userprc.txt' in the directory where you ran the command. Please upload these.

**Comment by mbalci420-hub** [comment]
I'm sorry but it's still the same shit again and again. :( I really appreciate your effort but as I said before, this motherboard sucks.

**Comment by ixjf** [comment]
These commands are not meant to fix your issue, but to help me figure out what is causing it.

**Comment by ixjf** [comment]
Will you try this, or should I close the issue?

**Comment by ixjf** [comment]
I'm closing the issue then.
