### ISSUE TITLE
Adding support to MSI Z390 Gaming Edge AC

### ISSUE THREAD

**Issue by rayan-adamczak** [ixjf/MSIRGB#179]
Hey, it would be nice if some day, you could add this motherboard to the compatible list.

I tried to install it, but I got a message saying that my mobo is not supported!

**Comment by ixjf** [comment]
Can't guarantee anything, sorry. If they don't work the same way as my motherboard, I'd be hardpressed to release software as it would be untested.

**Comment by ixjf** [comment]
Seems like it uses a different mechanism for controlling LEDs, in which case, I won't be able to add support for this myself. Closing this issue.
