### ISSUE TITLE
B550 unsupported (Ryzen 5600x)

### ISSUE THREAD

**Issue by AlainCh2** [ixjf/MSIRGB#183]
It would be nice to see some 5 AMD's series taken care of.

So far nobody should buy a B450 nowadays :-D

**Comment by Ankh-** [comment]
Yes please! I got a B550m Mortar

**Comment by ixjf** [comment]
Sorry, won't happen. I'm not adding support for any new motherboards. It seems they all use a different mechanism for LEDs.
