### ISSUE TITLE
"Failed to load driver."

### ISSUE THREAD

**Issue by kupokappa** [ixjf/MSIRGB#187]
"This could be either due to some program interfering with MSIRGB's driver, or it could be a bug. Please report this on the issue tracker at: https://github.com/ixjf/MSIRGB"

MSI B450 TOMAHAWK MAX, Windows 10 Pro 1909.

**Comment by ixjf** [comment]
Disable or uninstall Riot Vanguard, FACEIT anti-cheat, and all other such programs before running MSIRGB. They all block MSIRGB's driver from loading.

**Comment by kupokappa** [comment]
It was Riot Vanguard. Hopefully one day they'll have a workaround.

**Comment by ixjf** [comment]
Yes. I was supposed to contact them to see if they could make an exception but I haven't had the time yet to focus on this project. Think I'll do that today.
