### ISSUE TITLE
Colour picker should be changed to display only the 4096 available colours

### ISSUE THREAD

**Issue by ixjf** [ixjf/MSIRGB#19]

**Comment by SimoDax** [comment]
In case it helps, I generated a palette with only the 3375 pixels that are settable without approximations
Empty rows and columns could be deleted, the remaining spaces filled with the closest neighbour colour, and used with the current picker code
![picker](https://user-images.githubusercontent.com/12528611/53305652-57b79b80-3884-11e9-9ee6-3dfd3d243f83.png)

Another option would be to set the color inserting 0-15 values in text boxes and having the picker rectangle display a preview

**Comment by ixjf** [comment]
I would prefer if there was a colour picker. Still not sure how to do this. Probably will leave it like this for now.

**Comment by SimoDax** [comment]
This makes me wonder: what about the motherboards MSI sells stating "16 million colours"? Smells like burnt..

**Comment by ixjf** [comment]
As far as I know, all the motherboards that MSIRGB supports are advertised as having only 7 choices of colour. Those that do say 16 million colours all likely use a separate Renesas chip for LED control.

**Comment by ixjf** [comment]
Fixed.
