### ISSUE TITLE
Program doesn't work on Windows 7 & Server 2008 R2.

### ISSUE THREAD

**Issue by R3n001** [ixjf/MSIRGB#196]
The program crashes at launch on Windows 7, with a non-descriptive error.

I used Dependency Walker to profile the application, and got this.
![ScreenShot_20210205051402](https://user-images.githubusercontent.com/77039240/107027256-7e212980-6771-11eb-81e7-612c662f762e.png)

This is Event Viewer output from running the program normally.
![ScreenShot_20210205051604](https://user-images.githubusercontent.com/77039240/107027274-824d4700-6771-11eb-8203-07805bb485ae.png)
![ScreenShot_20210205051619](https://user-images.githubusercontent.com/77039240/107027277-84170a80-6771-11eb-94b5-0ec27b74455b.png)

**Comment by ixjf** [comment]
Only Windows 10 is supported. No plans to support any other OS. Time to move on, it's 2021.
