### ISSUE TITLE
How to remove script?

### ISSUE THREAD

**Issue by yourlifeupdated** [ixjf/MSIRGB#209]
Hello, I used the script on my B450 but I have a problem.

The led turned-off, but also the back fan in the case stopped working and now it does not start again.

How can i remove/uninstall the script?

**Comment by ixjf** [comment]
If you've already stopped the script in MSIRGB, then there's nothing else to remove. If you can't get the LEDs on again, you'll have to either run Mystic Light/Gaming Center, or if that doesn't work, clear the CMOS. You can try 3 different ways to do that:

1. Turn off the computer **AND** the power supply. Press the computer's power button for about 10 seconds. Reboot.
2. If the motherboard has a clear CMOS jumper, use that.
3. If all else failed, remove the CMOS battery for about a minute. Reboot.
