### ISSUE TITLE
Support for MSI B450M PRO-VDH V2

### ISSUE THREAD

**Issue by r0b985** [ixjf/MSIRGB#211]
MSIRGB works flawlessy on b450m "mortar" & "pro-vdh max" but "pro-vdh v2" outputs this error message when launching the tool:

![msirgb_error](https://user-images.githubusercontent.com/80977722/111833490-892fb380-88f2-11eb-8f72-886ff4689753.jpg)

**Comment by ixjf** [comment]
Almost certainly due to an anti-cheat running in the background. FACEIT, Vanguard and whatnot do not allow MSIRGB to run.

**Comment by r0b985** [comment]
Thank you very much, vanguard was running, now it works. Never thought of this could cause the problem.
