### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by EagL3-GIT** [ixjf/MSIRGB#213]
![image](https://user-images.githubusercontent.com/63203158/113483437-adb78e00-94a3-11eb-9dd2-6ec244335766.png)

**Comment by ixjf** [comment]
Vanguard and other anti-cheats must be disabled before running MSIRGB.

**Comment by Gash3d** [comment]
I am getting this same issue however i am not running a single anti-cheat. I noticed that i was getting this same type of problem when trying to use MSI Center/Dragon Center. My motherboard is the x470 Gaming Plus.

**Comment by ixjf** [comment]
Whatever problem you were having with MSI programs is not the same one as this since MSIRGB is completely independent from these other programs.

Either way, past experience tells me that you probably **are** running an anti-cheat, though unaware of it. Do you have any games installed?

**Comment by Gash3d** [comment]
Games i have installed are these paired with League of Legends & Valorant. I have Riot Vanguard disabled at startup and have restarted my PC many times afterwards. 
![image](https://user-images.githubusercontent.com/12701328/118407415-9fd25c80-b64e-11eb-8984-f4ffeedd440e.png)

**Comment by ixjf** [comment]
It seems that (at least) Apex Legends also uses a kernel-level anti-cheat that could be causing these problems. Could you run the following command on a command prompt and upload here the output file?

`driverquery /fo table /v > instdrivers.txt`

This will create a file `instdrivers.txt` in the directory where the command prompt was started. It will contain a list of all installed drivers on your system.

**Comment by Gash3d** [comment]
Here's the file 
[instdrivers.txt](https://github.com/ixjf/MSIRGB/files/6489853/instdrivers.txt)

**Comment by ixjf** [comment]
It seems that the Riot Vanguard driver is still running on your system.

**Comment by Gash3d** [comment]
I had no idea. I thought Stopping it at startup was enough. I uninstalled it and the software works now. Thank you so much!!!

**Comment by ixjf** [comment]
I believe there is a way to disable Vanguard without uninstalling it, but I'm not sure. I can't tell you precisely how because I've never used it.
