### ISSUE TITLE
Worked fine suddenly app can't start

### ISSUE THREAD

**Issue by ckchs** [ixjf/MSIRGB#24]
When i start program i got Failed to load. Please report this on the issue tracker at GitHub. 2 Weeks ago app worked fine. I tried redownload it but no help

**Comment by Nama** [comment]
Open the "Services" window and stop MSIRGB Script Service. Then start the tool again.

**Comment by ixjf** [comment]
Thanks. Yes, this a known issue that I haven't gotten around to dealing with yet. For the time being, Nama's solution should do.

**Comment by ixjf** [comment]
Fixed in v2.0.2.
