### ISSUE TITLE
We need MSI Z390 Gaming Pro Carbon support! 

### ISSUE THREAD

**Issue by Arrowka** [ixjf/MSIRGB#29]
Thats it! :)

**Comment by ixjf** [comment]
Can't do without a motherboard for testing. Anyway, doesn't that motherboard have better support for LED effects?

**Comment by Arrowka** [comment]
No it doesn't. For example i cant simulate "Orange".

**Comment by ixjf** [comment]
Right. That sucks. But the fact is that I can't guarantee a working program at all times without having a motherboard to develop it on - that's why the tool only supports a few select motherboards: because these work the same as mine.
