### ISSUE TITLE
MSI B350 Gaming Plus

### ISSUE THREAD

**Issue by matcho13579** [ixjf/MSIRGB#36]
I'm unable to get the exe working on the latest version (2.2.1.7) - error says that the vendor was not detected to be MSI, previously it worked fine (although no Mystic Light support), output from cmd:

C:\WINDOWS\system32>wmic baseboard get product,Manufacturer,version
Manufacturer                       Product                     Version
Micro-Star International Co., Ltd  B350 GAMING PLUS (MS-7A34)  4.0

**Comment by ixjf** [comment]
Can you try this DLL and confirm if it works now?
[MSIRGB.DLL.dll.zip](https://github.com/ixjf/MSIRGB/files/3145750/MSIRGB.DLL.dll.zip)

**Comment by matcho13579** [comment]
Yes, works fine, thanks!
