### ISSUE TITLE
MSI Z270 M7 not recognized

### ISSUE THREAD

**Issue by Martinocom** [ixjf/MSIRGB#38]
Hello!
My MoBo is on the supported list, but the program won't launch. It says to report this, so here I'm. Computer is fresh, just formatted.
![bug](https://user-images.githubusercontent.com/17514549/57552036-df348700-736a-11e9-8a22-f30abb6ff051.png)

**Comment by ixjf** [comment]
Could you run this command on the command line and tell me the output?

```
wmic path Win32_BaseBoard get Manufacturer
```

**Comment by Martinocom** [comment]
Here it is! (no admin priviledges)
![image](https://user-images.githubusercontent.com/17514549/57555377-69351d80-7374-11e9-91b3-a9b88de53e9c.png)

**Comment by ixjf** [comment]
Does it work with this DLL?

[MSIRGB.DLL.dll.zip](https://github.com/ixjf/MSIRGB/files/3168161/MSIRGB.DLL.dll.zip)

**Comment by Martinocom** [comment]
Worked, but shouldn't it have something more, like colours?
![image](https://user-images.githubusercontent.com/17514549/57558336-96d29480-737d-11e9-9134-31e11771c0b5.png)

**Comment by ixjf** [comment]
Alright, thanks, publishing the fix asap.

**Comment by ixjf** [comment]
By the way, can I add your motherboard to the list of verified working motherboards?

**Comment by Martinocom** [comment]
Sure! Happy to contribute :)

PS: Is there a way to set one colour without cycling? Like a "static blue"? I currently have all 8 colours set as same blue to achieve that.

**Comment by ixjf** [comment]
That's the only way to do it, really.

**Comment by Martinocom** [comment]
Np, thx for fixing it so quickly. To add some details, all RGBs around the mobo and also the led strip connected to the 4-pin RGB works perfectly.

Happy coding.
