### ISSUE TITLE
Add B450M Bazooka Plus to supported devices list

### ISSUE THREAD

**Issue by FadedCoder** [ixjf/MSIRGB#39]
This works perfectly with the motherboard (https://www.msi.com/Motherboard/B450M-BAZOOKA-PLUS.html).

Just the starting not supported message is annoying every time I open it. Also, is there any reference for the API? I'm planning on making a universal app for MysticLight, SteelSeries Engine and other lighting apps.

**Comment by FadedCoder** [comment]
My bad, everything is not as intended. The colors are reversed. (0xF00 is 0x0FF). Will commit a push fixing it soon.
Just having trouble opening the project on VS 2019.

**Comment by ixjf** [comment]
> Also, is there any reference for the API?
What API are you talking about?

**Comment by ixjf** [comment]
Also, this is #37.

**Comment by FadedCoder** [comment]
Gaming Plus is a different motherboard. I am submitting a PR for this motherboard as soon as I manage to compile it from VS2019. WHY CAN'T VISUAL STUDIO WORK FOR ONCE.

By API I meant like a reference document for the DLL. Nevermind that, the code is self explanatory.

**Comment by FadedCoder** [comment]
@ixjf have a question. Does the 8 colors switch randomly? Or in some order?

**Comment by ixjf** [comment]
It is a diferent motherboards but the behaviour is the same.

The colours change in the order from index 1 to 8.

**Comment by FadedCoder** [comment]
I was thinking of that too, but in my motherboard it goes from 1 to 8, then 8 to 1.

**Comment by FadedCoder** [comment]
@ixjf when I try to run motherboard support checking (the WMI connect part) on another app, I get an error access denied. But this does not happen on the original app for same code. How did you fix this?

**Comment by ixjf** [comment]
> I was thinking of that too, but in my motherboard it goes from 1 to 8, then 8 to 1.

I think that's correct.

> @ixjf when I try to run motherboard support checking (the WMI connect part) on another app, I get an error access denied. But this does not happen on the original app for same code. How did you fix this?

MSIRGB runs as administrator, that's probably why.

**Comment by ixjf** [comment]
Closing this as you already have a pull request open.

**Comment by bobalob** [comment]
Hey,

Not an issue since this is not a supported board, but just wanted to let you know this is working on a B450M Moratar Titanium board, however the RGB values are reversed. 

To get full red you need to set R=0, G=F and B=F. 
To get Yellow, R=0, G=0, B=F.
etc...

I **think** the B450M Mortar Titanium is just a B450M Mortar with a different paint job.

Thanks for taking the time to work on a sweet utility, even with colours reversed it's still way better than Mysic Light! 👍

**Comment by ixjf** [comment]
Thanks! It is most definitely an issue. I'll add it to the list of supported motherboards with a note.

2.2.1.3 should fix the reversed colours issue, though I can't tell you when that will be ready (can't work on MSIRGB any time soon due to university).
