### ISSUE TITLE
Am i just being stupid? xd

### ISSUE THREAD

**Issue by MajorLOLGaming** [ixjf/MSIRGB#47]
Do i have to uninstall the mystic lightning software? I had it uninstalled before and it seemed to make the hue wheel effect fade to white between every color. Installing the mystic light thing apparently fixed it... I'm confused :/

**Comment by ixjf** [comment]
No, you don't. As long as it isn't running at the same time as MSIRGB, there should be no problem. If you can reproduce the error, please show me how.

**Comment by MajorLOLGaming** [comment]
seems to be fixed now. idk how :/
