### ISSUE TITLE
msi b450m pro vdh plus is working

### ISSUE THREAD

**Issue by ciriys** [ixjf/MSIRGB#53]
i dont know how to report this but i have installed and ran it and it works, even with a random cheapo rgb strip

**Comment by ixjf** [comment]
Thanks! Will add to the list.

**Comment by ixjf** [comment]
Do you get a warning about unsupported model when you start MSIRGB? I'm trying to figure out which revision your motherboard is, since from my knowledge revisions 1.x and 2.x shouldn't work.

**Comment by ciriys** [comment]
> Do you get a warning about unsupported model when you start MSIRGB? I'm trying to figure out which revision your motherboard is, since from my knowledge revisions 1.x and 2.x shouldn't work.

yes, i do get the warning at the beginning of app startup but as far as i can tell everything works fine the colors are accurate and even the pre loaded lua scripts work as intended
i am not exactly sure what revision my motherboard is, if you're willing to tell me how to find it, i will try my best to find it and respond to you with the revision, i will attach a cpuid screenshot of the motherboard, hope that helps
also thank you for making such an awesome software with a nice gui for dumb-dumbs like me :)
![Capture](https://user-images.githubusercontent.com/54254821/63902839-e9f75280-ca13-11e9-989b-ed6dcd0fe08e.PNG)

**Comment by ixjf** [comment]
I'm assuming "7.0" is the version number, but run this in a command prompt to make sure:

`wmic path Win32_BaseBoard get Version`

If it is indeed 7.0, then this is a newer revision and I'll have to add it to the list.

**Comment by ciriys** [comment]
yup, you were right it is version 7.0 
![Capture](https://user-images.githubusercontent.com/54254821/64065854-9e16fa00-cc1b-11e9-82a5-8e421a2d51c9.PNG)

**Comment by ixjf** [comment]
Alright, thanks!
