### ISSUE TITLE
MSI B350M Gaming PRO (about Music Sync)

### ISSUE THREAD

**Issue by Albatroza** [ixjf/MSIRGB#54]
This Software works perfectly, I need to do Music sync (not like official msi app because it's very slow reaction) how can we do this?
(Windows 10 Ultimate Version 1903 (lastest) 64Bit)

**Comment by ixjf** [comment]
I currently can't work on MSIRGB but if someone wants to implement it, I'd be glad to look into it. Should be a matter of adding a scripting interface to some sound library in the script service.

**Comment by ixjf** [comment]
Closing as it is a duplicate of #119.
