### ISSUE TITLE
Script does not run after resuming from sleep

### ISSUE THREAD

**Issue by mrcaseyrose** [ixjf/MSIRGB#55]
My script runs just fine when opening the app, or during the initial boot of the computer; however, if I put the computer to sleep and resume again, it does not run and the LEDs return to their default (all white) state.

**Comment by ixjf** [comment]
This may be the same as #43. I'll look into it when I can (but can't promise when).

**Comment by mrcaseyrose** [comment]
Hey thanks for taking the time to reply. Does it work fine for others upon resuming standby? I was thinking it was a limitation of the RGB controller in the motherboard.

**Comment by ixjf** [comment]
I don't honestly know what it is, but it's probably something that I can handle from MSIRGB, _if_ it's not a bug.

**Comment by Cris--** [comment]
[Here my solution](https://github.com/ixjf/MSIRGB/issues/69#issuecomment-566262559) with Windows Task Scheduler..

**Comment by ixjf** [comment]
Closing as it is a duplicate of #43. Please refer to that issue for info on the status of the fix.
