### ISSUE TITLE
Works on MSI H270 Gaming Pro Carbon

### ISSUE THREAD

**Issue by HighwayChile** [ixjf/MSIRGB#56]
Thank you so much! MSI Gaming App blows!

I found one bug so far, If I set the step duration to 256 it seems to have a lot of trouble displaying the color green (0f0) It actually shows a beautiful display of RGB that could be desirable. So far this has only happened when the value was set to 256. I may debug this in future.

**Comment by ixjf** [comment]
Alright, can you describe the problem a bit further? What do you mean by trouble displaying the colour green?

**Comment by HighwayChile** [comment]
Yes, it cycles incredibly fast through a large range of colors when I try to display green. It flashes through RGB at high speed. It flashes one color, then another color, then another color, so fast that it is dazzling. It happens when I set the color to green (0f0) and have the step duration set to 256 and not running scripts from the menu. Breathing effect seems to make no difference with the bug. (I have not tried debugging yet.) 

I haven't played with the program much more. I just set it to a theme I liked and have been watching my voltages. Everything looks normal so far as that goes.

**Comment by ixjf** [comment]
In that case, the only thing I can do is do some research on your motherboard. Maybe it works slightly differently. But I can't promise to be able to work on this any time soon (or MSIRGB in general).

**Comment by HighwayChile** [comment]
Hey, it's all good. I have a job too, hehe. I was just letting other people
know. I actually tried to replicate the flashing lights issue once and
wasn't able to. I didn't try all the settings, but, it may have been a
minor bug after running one of the scripts. Anyway, I haven't seen any
problems since, so I am using your software! It works great and it has more
options/fewer restrictions than MSI's stupid "gaming app," which seizes
control of some audio options, making Starcraft 2 only playable without
audio, lol. Thanks again!

**Comment by ixjf** [comment]
Alrigut, that's good. I'll still try to look into this when I can, though.
