### ISSUE TITLE
Not openning in B350 Tomahawk

### ISSUE THREAD

**Issue by mamad0901-sys** [ixjf/MSIRGB#60]
when I accept the risks , nothing happens . I checked task manager and windows problem reporter was active .

Windows 10 Build 18362
B350 tomahawk with rgb strip in header

I also should note that I use msi gaming app to control rgb header with 7 colours becuase mystic light doesn't work in this motherboard. I deleted gaming app but it solved nothing .

**Comment by mamad0901-sys** [comment]
Solved by closing msi afterburner 
its working thanks!

**Comment by ixjf** [comment]
Does it always fail to work with MSI Afterburner working?

**Comment by mamad0991** [comment]
Yes . I should always close it .

**Comment by ixjf** [comment]
Alright. That's good. I'll keep this in mind and see if there's any way to work around it without changing that setting.
