### ISSUE TITLE
x570-a support

### ISSUE THREAD

**Issue by sticker592** [ixjf/MSIRGB#63]
Has anyone tried it on the new msi x570-a boards or is it known from the sdk that the boards won't work?

**Comment by sticker592** [comment]
mystic light is not supported on my system even thought the msi site says it should be so I assume it isn't supported

**Comment by ixjf** [comment]
The X570-A PRO has an NCT6797 chip and has LED connectors, so it's possible it works. I can't confirm MSIRGB is compatible any time soon, so your only chance is trying it out, but I can't guarantee it won't do any harm.
