### ISSUE TITLE
MSI X470 Gaming Pro with Corsair Vengeance RGB Pro

### ISSUE THREAD

**Issue by Biddel** [ixjf/MSIRGB#64]
First of all: thank you for this great piece of software.

Just one little issue occured: my RAM ( Corsair Vengeance RGB Pro) won't sync with the other parts, it just stays at one color. Can someone help?

Thanks!

**Comment by ixjf** [comment]
Unfortunately, MSIRGB only changes motherboard LED settings. Changing your RAM RGB colour requires using a Corsair-specific API.

**Comment by Wtcheesecakes** [comment]
i think you need to use the icue software for that (icue is pretty good tho :) )
