### ISSUE TITLE
MSI B350 Gaming Pro Carbon is working

### ISSUE THREAD

**Issue by PAlbrechtHH** [ixjf/MSIRGB#66]
I have been using this great software for 2 months now on my MSI B350 Gaming Pro Carbon mainboard :-)

**Comment by retrofero** [comment]
Hi! I'm trying to install this myself as well but didn't see the .exe file anywhere to start the program.
Am I missing something?

**Comment by PAlbrechtHH** [comment]
MSIRGB.exe

**Comment by ixjf** [comment]
Thanks!
