### ISSUE TITLE
B450 Tomahawk does work with msirgb

### ISSUE THREAD

**Issue by sirBBBmlg** [ixjf/MSIRGB#67]
Title says everthing ( U safed my ass with that programmty)

**Comment by sirBBBmlg** [comment]
it isnt loading the scripts right after a few start ups

**Comment by ixjf** [comment]
I think this is a known bug. Does this:

https://github.com/ixjf/MSIRGB/issues/43#issuecomment-525195336

describe more or less your problem?

**Comment by ixjf** [comment]
Closing as it is a duplicate of #43. Please refer to that issue for info on the status of the fix.
