### ISSUE TITLE
MSIRGB vs Mystic Light performance issues?

### ISSUE THREAD

**Issue by Nintari** [ixjf/MSIRGB#68]
Just seeing if MSIRGB has any issues like I experience with MysticLight. MysticLight at this point is unuseable for me as it causes major performance issues. For example when playing a game I get constant dips in performance, when watching a youtube video It pauses and stutters and gives me a buzzing sound when active. If I close out the MysticLight service and LEDKeeper this all goes away. Just needing something that doesn't cause these issues.

**Comment by ixjf** [comment]
I'm not aware of any if these issues with MSIRGB, but Mystic Light shouldn't cause that either.
