### ISSUE TITLE
Any command line arguments supported?

### ISSUE THREAD

**Issue by przekrencone** [ixjf/MSIRGB#71]
For example calling "MSIRGB.exe f f f" turns LED white.

**Comment by ixjf** [comment]
No, there aren't. What would be the use case?

**Comment by Cris--** [comment]
Start minimized with e.g. Windows Autoruns with a specific color and maybe brightness. ^^
MSIRGB.exe #ffffff b50

**Comment by ixjf** [comment]
You can already do this with a script. As for brightness, it's not supported by the hardware as far as I know.

**Comment by przekrencone** [comment]
You can of course change brightness by changing colors down. F->8
On my motherboard (b350m mortar) red channel works very smooth, but blue always stays at 100%

**Comment by Cris--** [comment]
Can anyone share a script with one color only and no fade please?

**Comment by przekrencone** [comment]
Give me 10minuts, i have it on pc

**Comment by przekrencone** [comment]
> Can anyone share a script with one color only and no fade please?
Here you go
[Solid Green.zip](https://github.com/ixjf/MSIRGB/files/3995096/Solid.Green.zip)
