### ISSUE TITLE
No "MSIRGB.exe" in files

### ISSUE THREAD

**Issue by Collcroc123** [ixjf/MSIRGB#72]
The "How to Install" section says to run "MSIRGB.exe", but there is no .exe anywhere in the files. How do I run the program? Do I have to build? If so, I have no idea how to build in Visual Studio.

**Comment by ixjf** [comment]
I just checked and it is. Make sure you haven't skipped step 3.

**Comment by Collcroc123** [comment]
ah, there we go! apparently I downloaded the master file. thanks!
