### ISSUE TITLE
Scripts: interpolating between colours

### ISSUE THREAD

**Issue by maelremrem** [ixjf/MSIRGB#74]
Hello
I'm trying to make a script
I want to lerp from 3 colors but I can't find any methods
Do you have any idea to do so ?
I tried to modify the Wheel Hue Script but nothing is working...

**Comment by ixjf** [comment]
I'm sorry I couldn't answer your question in time. Do you still need help? Interpolating should be pretty simple if you use HSV. MSIRGB has methods for converting RGB to HSV and vice-versa.
