### ISSUE TITLE
MSI Mainboard but wrong BIOS DMI information - MSIRGB force stopped for "incompatible Mainboard"

### ISSUE THREAD

**Issue by ClimbTheGrind** [ixjf/MSIRGB#79]
My BIOS DMI information is wrong somehow (i did not change it, but it is not the original one).
It says some random numbers under "Manufactorer" and "Mainboard Model".
So i think MSIRGB does control this to match only on compatible boards.
As a result MSIRGB wont launch. It says it does this "to protect my hardware".
I have got a MSI B350 Gaming Pro Carbon, so i would like to manually override that message as i KNOW that my board should be supported (and the MSI Mystic light is...not working for the same reason, i think.) So this program should be my solution over MSI apps and editing my Mainboard DMI, i think.

**Comment by ixjf** [comment]
MSIRGB should run either way if you ignore the warning message at start. However, your motherboard is not known to be compatible, so do it at your own risk.
