### ISSUE TITLE
B450 Tomahawk max reversed colors

### ISSUE THREAD

**Issue by nagynorbert97** [ixjf/MSIRGB#85]
The whole thing works fantastic when i run the Hue script and that was the reason why i donwloaded it, but all the manually set colors are reverse. Is there any easy fix to do it myself?

**Comment by ixjf** [comment]
Currently, the only way is to fork the branch, apply the pull request #48, and build MSIRGB yourself (or at least MSIRGB.DLL, the other binaries don't need to be rebuilt).

**Comment by ixjf** [comment]
MSIRGB v2.3.0 fixes the reversed colour issue. Please try the new version.

**Comment by ixjf** [comment]
Closing as it is a duplicate of #139.
