### ISSUE TITLE
Need a sample to use the dll to a c# project

### ISSUE THREAD

**Issue by cednieb** [ixjf/MSIRGB#86]
Hi

That works but ...

Can you provide a sample to use the dll to an existing project ( c# ) , please ?

I am using the librehardwaremonitor dll in this c# project .

My goal is to change the color of my Ryzen 1700 fan on Msi b350  Tomahawk .

Green when it is cold , orange and red when it is hotter .

**Comment by ixjf** [comment]
You can see how it is done here: https://github.com/ixjf/MSIRGB/blob/master/MSIRGB.GUI/MainWindowModel.cs

The DLL is attached to the MSIRGB.GUI project as a .NET assembly dependency.

**Comment by cednieb** [comment]
when I add the dll in references , it says incorrect format at launch

**Comment by cednieb** [comment]
x64 as target and it works .
