### ISSUE TITLE
"Failed to load driver"

### ISSUE THREAD

**Issue by elelunicy** [ixjf/MSIRGB#9]
So the last time I used MSIRGB a couple weeks ago it worked perfectly without a problem. And now it no longer launches it always says "Failed to load driver." What driver is it talking about? I have no clue what could have gone wrong.

**Comment by ixjf** [comment]
It's talking about the driver MSIRGB uses to control the hardware. Are you using the same version as you had been before or did you upgrade since the last time? And which version is it?

**Comment by elelunicy** [comment]
I was using v1.0.0 and it didn't work today. I then downloaded the latest v1.0.5 but it also has the same problem persist.

**Comment by ixjf** [comment]
Could you open a command prompt as administrator and run the following command `sc query MSIRGB.Driver`? It will query the Windows' service manager and tell you whether the driver service is installed or not. That might give me a clue.

**Comment by elelunicy** [comment]
```
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.
```

Apparently it's not.

**Comment by ixjf** [comment]
Could you replace your MSIRGB.DLL.dll with this one? Once you've done that, start MSIRGB again. It'll likely crash again. Once the tool closes, look for a 'debug_log.txt' in the folder where MSIRGB is and paste it here, please.

[MSIRGB.DLL.dll.zip](https://github.com/ixjf/MSIRGB/files/2774853/MSIRGB.DLL.dll.zip)

**Comment by elelunicy** [comment]
```
driver .sys saved to system32 dir
driver service installed
failed to start driver service
driver service was not already running
start_drv failed
driver failed to load
```

**Comment by ixjf** [comment]
Crap, forgot to log the important bit. Please try again.
[MSIRGB.DLL.dll.zip](https://github.com/ixjf/MSIRGB/files/2774874/MSIRGB.DLL.dll.zip)

**Comment by elelunicy** [comment]
Now there is a new line "error: 183"

**Comment by ixjf** [comment]
And everything else is the same?

**Comment by elelunicy** [comment]
Yup

**Comment by ixjf** [comment]
Just to make sure it's not some random problem - have you tried restarting the computer? If the error line appears along with the exact same output on the log file as before, the error code makes no sense at all.

**Comment by elelunicy** [comment]
Yes I've restarted it multiple times and it's always the same. Here's the full log:

```
driver .sys saved to system32 dir
driver service installed
failed to start driver service
driver service was not already running
error: 183
start_drv failed
driver failed to load
```

**Comment by ixjf** [comment]
Okay, try this DLL, then start MSIRGB again. It'll crash as usual. After that, open a command prompt as administrator and run `sc query MSIRGB.Driver`. If it doesn't say it's not installed (as it shouldn't), run `sc start MSIRGB.Driver` and send me the output.
[MSIRGB.DLL.dll.zip](https://github.com/ixjf/MSIRGB/files/2774916/MSIRGB.DLL.dll.zip)

**Comment by elelunicy** [comment]
```
[SC] StartService FAILED 183:
Cannot create a file when that file already exists.
```

**Comment by ixjf** [comment]
Does everything else on your computer work normally? I can't see this being an error from the driver itself (which I don't personally maintain), and it's clearly not a fault of MSIRGB since the driver service doesn't start from the command line. Did you do any Windows updates since the last time MSIRGB worked?

**Comment by ixjf** [comment]
Just to make sure it isn't some weird ass bug related to file paths: search for 'registry editor' on start menu (just type it after opening the start menu), and replace the contents of the address bar at the top of the window that opens with 'Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\MSIRGB.Driver'. What does 'ImagePath' say?

**Comment by elelunicy** [comment]
Yes my computer works as normal. Windows auto installed the cumulative 2019-01 update recently and that's about it. I also swapped a new CPU but that shouldn't affect drivers.

'ImagePath' says `\??\C:\WINDOWS\system32\drivers\inpoutx64.sys`

**Comment by ixjf** [comment]
Looks about right. I have no clue why it's failing.

**Comment by ixjf** [comment]
Any way you could run this tool? https://docs.microsoft.com/en-us/sysinternals/downloads/winobj
Start it, and choose "GLOBAL??" on the left. Look for a name "inpoutx64" or symlink "\Device\inpoutx64". Tell me if there is one.

**Comment by elelunicy** [comment]
Yes it's there.

**Comment by ixjf** [comment]
Does it still appear after you run `sc delete MSIRGB.Driver` on a command prompt with admin privileges?

**Comment by elelunicy** [comment]
It's still there.

**Comment by ixjf** [comment]
I might be on to something then. That shouldn't be there. No idea whether it was a bug in Windows or the driver, but that should disappear the moment the driver stops. I'll have to do some digging, but it's getting late, so I'll look into that tomorrow.

**Comment by ixjf** [comment]
Driver objects should be deleted on restart, something I didn't consider yesterday. Meaning the driver initialization code must be executing. Weird.

**Comment by elelunicy** [comment]
Could it be because something else I have is also using "inpoutx64"? It’s always there the moment after I log in Windows.

**Comment by ixjf** [comment]
To answer your question, yes. Things would go wrong if the driver was being used elsewhere, since the driver tries to register the global object "inpoutx64" in the two instances. Let me write something quick to test that hypothesis.

**Comment by elelunicy** [comment]
Yes it’s there before I run MSIRGB.

**Comment by ixjf** [comment]
Try this. Tell me if it works. Debug log is in 'debug_log.txt', though if it works I won't need it.
[MSIRGB.DLL.dll.zip](https://github.com/ixjf/MSIRGB/files/2775519/MSIRGB.DLL.dll.zip)

**Comment by elelunicy** [comment]
It worked. Thanks!

**Comment by ixjf** [comment]
Great! I'll push the fix officially asap then.

**Comment by ixjf** [comment]
Could you test this and tell me if it's working fine for you before I publish it?
[Release.zip](https://github.com/ixjf/MSIRGB/files/2775827/Release.zip)

**Comment by elelunicy** [comment]
Yes it works.

**Comment by ixjf** [comment]
Thanks.
