### ISSUE TITLE
Any way to get this working with peripherals?

### ISSUE THREAD

**Issue by RafeeSamith** [ixjf/MSIRGB#96]
I know this is for motherboards and their RGB headers only but I've been trying to set my MSI CLUTCH GM11's RGB to orange forever and Dragon Center only lets me choose between 7 colors. My lack of experience in C++ and Visual Studio isn't helping either since I tried using SimoDax's tool but to no avail. Any ideas? Thanks in advance c:

**Comment by Mayravixx** [comment]
Same here, I've been told previously that MSI's Mystic Light software can be used for Razer products since Synapse is now shitting the bed, and somehow I ended up here. That being said though, I would like to see this program working with my GPU if possible, since I do have an MSI RX 580

**Comment by ixjf** [comment]
https://gitlab.com/CalcProgrammer1/OpenRGB

Might do what you want.
