### ISSUE TITLE
Z390 Gaming Pro Carbon AC support?

### ISSUE THREAD

**Issue by joker364** [ixjf/MSIRGB#99]
just seeing if this program is still being updated at all and if there's any support for the z390 chipset. MSI Mystic Light is very limiting. Especially when selecting multiple parts. When i used Aura i was even able to change the individual LEDs on my RAM.

**Comment by Wtcheesecakes** [comment]
Hi there I have a z390-A pro and can confirm it works, im sure theyre pretty similair

**Comment by ixjf** [comment]
Thanks @Wtcheesecakes for the feedback. However, different motherboards, however similar, may have different mechanisms. The Z390 Gaming Pro Carbon AC doesn't seem to be supported by MSIRGB.
